const COLOR_LIGHT_GRAY = "#DCDCDC"
const COLOR_MED_GRAY = "#606060"
const COLOR_TEAL = "#008080"
const COLOR_DIM_YELLOW = "#ffc40c"
const COLOR_ORANGE_RED = "#FF4500"

const CANVAS_W = 600
const CANVAS_H = 750

const TEXT_SIZE_CHOOSE_A_SIM = 25
const TEXT_Y_CHOOSE_A_SIM = 10 + TEXT_SIZE_CHOOSE_A_SIM/2
const BTN_Y = TEXT_Y_CHOOSE_A_SIM + 25
const BTN_HORIZONTAL_SPACING = 2
const BTN_W_SPACE = CANVAS_W/5
const BTN_W = BTN_W_SPACE - 2*BTN_HORIZONTAL_SPACING
const BTN_H = 50

const TEXT_SIZE_R = 15
const TEXT_Y_R = BTN_Y + BTN_H + 10 + TEXT_SIZE_R/2

const FIELD_MARGIN = 10
const FIELD_START_Y = TEXT_Y_R + TEXT_SIZE_R/2 + FIELD_MARGIN

const SIM_COMPLETE_THRESH = 3
const SIM_SPEED_DEFAULT = 1
const DAY_LENGTH = 30

const SOCIAL_DISTANCE_STRENGTH_DEFAULT = 10
const INFECTION_INTERVAL_DEFAULT = DAY_LENGTH
const INFECTION_RATE_DEFAULT = 0.2
const INFECTIOUS1_INTERVAL_DEFAULT = 4*DAY_LENGTH
const INFECTIOUS2_INTERVAL_DEFAULT = 10*DAY_LENGTH

// Simple
const POINT_RADIUS_DEFAULT = 4
const INFECTION_RADIUS_DEFAULT = 16

// Central Location
const CENTRAL_LOC_SIZE = 16
const CENTRAL_LOC_SENDER_INTERVAL = 1
const CENTRAL_LOC_POINT_RADIUS = POINT_RADIUS_DEFAULT
const CENTRAL_LOC_INFECTION_RADIUS = INFECTION_RADIUS_DEFAULT

// Communities
const COMMUNITIES_SENDER_INTERVAL = 1
const COMMUNITIES_POINT_RADIUS = 3
const COMMUNITIES_INFECTION_RADIUS = 12